AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation template for creating resources for LDF-POC

Parameters:
  BucketName:
    Type: String
    Description: The name of the S3 bucket. Bucket names must be globally unique.
  RoleName:
    Type: String
    Description: The role that should be assumed by databricks for accessing the S3 bucket.
  PolicyName:
    Type: String
    Description: IAM inline policy that grants permissions to the Databricks role
  DatabricksAccountId:
    Type: String
    Description: AWS account ID that Databricks uses to assume this role.
  ExternalID:
    Type: String
    Description:  The external ID for the role. Databricks uses this to prevent confused-deputy.

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
  DatabricksStorageCredentialRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref RoleName
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Principal:
              # Databricks side account that will assume this role
              AWS: !Sub "arn:aws:iam::${DatabricksAccountId}:root"
            Condition:
              StringEquals:
                # ExternalId from Databricks (prevents confused-deputy)
                sts:ExternalId: !Ref ExternalID
      ManagedPolicyArns:
      - !Ref DatabricksStorageCredentialPolicy
  # Permissions this role has once Databricks assumes it
  DatabricksStorageCredentialPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Ref PolicyName
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - s3:GetObject
              - s3:PutObject
              - s3:DeleteObject
              - s3:ListBucket
              - s3:GetBucketLocation
              - s3:ListBucketMultipartUploads
              - s3:ListMultipartUploadParts
              - s3:AbortMultipartUpload
            Resource:
              - !GetAtt S3Bucket.Arn
              - !Sub "${S3Bucket.Arn}/*"


Outputs:
  BucketName:
    Description: "Name of the S3 bucket created"
    Value: !Ref S3Bucket