name: Deploy S3 Databricks CloudFormation Stack

on:
  workflow_dispatch:
    inputs:
      stack_name:
        description: 'Deploy S3, roles and trust policy between S3 account and Databricks.'
        required: true
        default: 'databricks-s3-stack'

# permissions:
#   id-token: write
#   contents: read

env:
  AWS_REGION: eu-west-1
  STACK_NAME: ${{ github.event.inputs.stack_name || 'databricks-s3-stack' }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Validate CloudFormation template
        run: |
          aws cloudformation validate-template \
            --template-body file://s3bucket.yaml \
            --region ${{ env.AWS_REGION }}

      - name: Deploy CloudFormation stack
        run: |
          aws cloudformation deploy \
            --template-file s3bucket.yaml \
            --stack-name ${{ env.STACK_NAME }} \
            --parameter-overrides file://params.json \
            --capabilities CAPABILITY_NAMED_IAM \
            --region ${{ env.AWS_REGION }} \
            --no-fail-on-empty-changeset

      - name: Get stack outputs
        run: |
          aws cloudformation describe-stacks \
            --stack-name ${{ env.STACK_NAME }} \
            --query 'Stacks[0].Outputs' \
            --region ${{ env.AWS_REGION }}

      - name: Notify deployment status
        if: always()
        run: |
          echo "Stack deployment completed for: ${{ env.STACK_NAME }}"